Repository getninjas/gaiden, pull requests merged in 2018-02, with the labels that each got.

#153 Adding Card variation - Citation
  docs/demo/gaiden-css/components/card/centered.html
  docs/demo/gaiden-css/components/card/citation.html
  docs/demo/gaiden-css/components/card/custom.html
  docs/demo/gaiden-css/components/card/demo.html
  docs/demo/gaiden-css/components/card/grid.html
  docs/demo/gaiden-css/components/card/highlighted.html
  docs/demo/gaiden-css/images/icons/check_accept.svg
  src/scss/components/_card-citation.scss
  src/scss/components/_card.scss
  src/scss/components/_icon.scss
  src/scss/components/_price_variation.scss
  src/scss/components/form/_checkbox.scss
  src/scss/components/form/_radio.scss
  src/scss/components/form/_steps.scss
  src/scss/gaiden.scss
  src/scss/generic/_links.scss
  src/scss/tools/mixins/_flex.scss
  src/scss/tools/mixins/_grid.scss
Labels: to review

#155 Create review card
  docs/demo/gaiden-css/components/card/review.html
  src/scss/components/_card-review.scss
  src/scss/components/_card.scss
  src/scss/gaiden.scss
Labels: to review

#156 Change container subtitle size
  src/scss/generic/_heading.scss
Labels: to review

#157 Create new list modifiers
  docs/demo/gaiden-css/components/list/on_column/demo.html
  docs/demo/gaiden-css/components/list/with_icons/demo.html
  docs/demo/gaiden-css/components/list/with_row_icons/demo.html
  docs/demo/gaiden-css/images/app-badges/app_store.png
  docs/demo/gaiden-css/images/app-badges/google_play.png
  src/scss/components/_list.scss
Labels: to review

#160 Updates List Component
  docs/demo/gaiden-css/components/list/demo.html
  docs/demo/gaiden-css/components/list/links_list/demo.html
  docs/demo/gaiden-css/components/list/on_column/demo.html
  docs/demo/gaiden-css/components/list/stacked/demo.html
  docs/demo/gaiden-css/components/list/stacked/using_grid_system/demo.html
  docs/demo/gaiden-css/components/list/using_grid_system/demo.html
  docs/demo/gaiden-css/components/list/with_icons/demo.html
  docs/demo/gaiden-css/components/list/with_row_icons/demo.html
  docs/demo/gaiden-css/components/list/with_title/demo.html
  src/scss/components/_list.scss
Labels: enhancement, minor

#161 Fix width card in IE 10.
  src/scss/components/_card-citation.scss
  src/scss/components/_card-profile.scss
  src/scss/components/_card.scss
Labels: bug
